const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
const {createApiKeys,createLimiter}=require('./api-keys.cjs');
test('hash-only storage, ownership, multiple keys, revocation, deleted accounts and limits',()=>{const folder=fs.mkdtempSync(path.join(os.tmpdir(),'bot4u-keys-'));let exists=true;try{const store=createApiKeys(folder,{userExists:()=>exists});const a=store.create('alice','Production'),b=store.create('alice','Testing');assert.notEqual(a.token,b.token);assert.equal(store.verify(a.token).username,'alice');assert.equal(store.verify('bad'),null);assert.equal(store.revoke('bob',a.key.id),false);assert.equal(store.list('bob').length,0);const persisted=fs.readFileSync(path.join(folder,'api-keys',a.key.id+'.json'),'utf8');assert.ok(!persisted.includes(a.token));assert.ok(!JSON.stringify(store.list('alice')).includes(a.token));assert.ok(!JSON.stringify(store.list('alice')).includes('hash'));assert.ok(store.list('alice').find(k=>k.id===a.key.id).lastUsedAt);store.revoke('alice',a.key.id);assert.equal(store.verify(a.token),null);assert.ok(store.verify(b.token));exists=false;assert.equal(store.verify(b.token),null);let time=0;const limit=createLimiter({limit:2,now:()=>time});assert.ok(limit('a'));assert.ok(limit('a'));assert.equal(limit('a'),false);time=60001;assert.ok(limit('a'))}finally{fs.rmSync(folder,{recursive:true,force:true})}});
test('HTTP signup/login and shared API routes enforce key and account boundaries',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'bot4u-http-'));let child,logs='';try{for(const f of fs.readdirSync(__dirname))if(/\.(cjs|txt)$/.test(f))fs.copyFileSync(path.join(__dirname,f),path.join(root,f));fs.cpSync(path.join(__dirname,'dist'),path.join(root,'dist'),{recursive:true});fs.mkdirSync(path.join(root,'.local'));fs.writeFileSync(path.join(root,'.local','telephony.json'),'{}');const port=45000+Math.floor(Math.random()*10000),base='http://127.0.0.1:'+port+'/ai';child=spawn(process.execPath,['server.cjs'],{cwd:root,env:{...process.env,PORT:String(port),BASE_PATH:'/ai',PUBLIC_ORIGIN:'',GEMINI_API_KEY:'test-only',NODE_PATH:path.join(__dirname,'node_modules')},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);let ready=false;for(let i=0;i<100;i++){try{if((await fetch(base+'/api/auth/status')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,50))}assert.ok(ready,logs);
const call=async(route,{method='GET',cookie,token,body}={})=>{const r=await fetch(base+route,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,redirect:'manual'});const data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]}};
const signup=await call('/api/auth/signup',{method:'POST',body:{username:'testuser',password:'test-password-123'}});assert.equal(signup.status,200);const cookie=signup.cookie;
const create=await call('/api/keys',{method:'POST',cookie,body:{name:'Main'}});assert.equal(create.status,201);const token=create.data.token,id=create.data.key.id;
assert.equal((await call('/api/v1/scripts')).status,401);assert.equal((await call('/api/v1/scripts',{token:'wrong'})).status,401);assert.equal((await call('/api/v1/scripts',{cookie})).status,401);
assert.equal((await call('/api/v1/scripts?mode=outbound',{token,method:'PUT',body:{script:'Answer politely.'}})).status,200);assert.equal((await call('/api/script?mode=outbound',{cookie})).data.script,'Answer politely.');
assert.equal((await call('/api/v1/calls',{token,method:'POST',body:{number:'+919890267326'}})).status,403);
assert.equal((await call('/api/keys',{token})).status,401);assert.equal((await call('/api/v1/auth/signup',{token,method:'POST',body:{}})).status,404);
const other=await call('/api/auth/signup',{method:'POST',body:{username:'otheruser',password:'test-password-123'}});assert.equal((await call('/api/keys/'+id,{cookie:other.cookie,method:'DELETE'})).status,404);assert.equal((await call('/api/keys',{cookie:other.cookie})).data.keys.length,0);
const second=await call('/api/keys',{method:'POST',cookie,body:{name:'Second'}});const list=await call('/api/keys',{cookie});assert.ok(!JSON.stringify(list).includes(token));assert.equal((await call('/api/keys/'+id,{cookie,method:'DELETE'})).status,200);assert.equal((await call('/api/v1/scripts',{token})).status,401);assert.equal((await call('/api/v1/scripts',{token:second.data.token})).status,200);
assert.equal((await call('/api/auth/login',{method:'POST',body:{username:'testuser',password:'test-password-123'}})).status,200);assert.ok(!logs.includes(token));assert.ok(!logs.includes(second.data.token));
}finally{if(child){child.kill();await new Promise(resolve=>child.once('exit',resolve))}fs.rmSync(root,{recursive:true,force:true})}});

